### ISSUE TITLE
While Testing I have a FetchXML that errors

### ISSUE THREAD

**Issue by AGenius** [abtevrythng/FetchXML-to-SQL#4]
Whilst testing this for my own use I decided to try a few FetchXML's that we have working in Dynamics 

This one fails with an error

`<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false">
    <entity name="incident">
        <attribute name="prioritycode" />
        <attribute name="ticketnumber" />
        <attribute name="title" />
        <attribute name="customerid" />
        <attribute name="new_contactname" />
        <attribute name="new_createdon" />
        <attribute name="statuscode" />
        <attribute name="ownerid" />
        <order attribute="prioritycode" descending="false" />
        <order attribute="ticketnumber" descending="false" />
        <filter type="and">
            <filter type="and">
                <filter type="or">
                    <condition attribute="ownerid" operator="eq-userid" />
                    <condition attribute="ownerid" operator="eq" uiname="Development" uitype="team" value="{6089E83B-1F77-E411-B232-00155D644382}" />
                </filter>
                <condition attribute="statecode" operator="eq" value="0" />
            </filter>
        </filter>
        <link-entity name="account" from="accountid" to="customerid" visible="false" link-type="outer" alias="a_4b5945b8a4a64613afc1ae1d5e6828c7">
            <attribute name="telephone1" />
        </link-entity>
        <attribute name="incidentid" />
    </entity>
</fetch>`

mainFiltersList.Add(new mainFilters(mainFilter.ParentNode.Attributes["name"].InnerText, mainFilter.Attributes["type"].InnerText.ToUpper(), mainFilter.ChildNodes[i].Attributes["attribute"].InnerText, convertOperator, ""));

System.NullReferenceException

Any ideas

**Comment by Schui1024** [comment]
i'm having the same issue, this app would be a wonder if it didn't crash out like this. 
Any chance of a review of the app for this issue? The developer probably doesn't realise but there's nothing on the internet that does what this app does.

**Comment by AGenius** [comment]
I gave up with this.  however the issue is with the fact the fetch xml has no attribute tag for the multi level filter types

its not dealing with no "attribute" in this section 
`
 <filter type="and">
            <filter type="and">
                <filter type="or">
                    <condition attribute="ownerid" operator="eq-userid" />
                    <condition attribute="ownerid" operator="eq" uiname="Development" uitype="team" value="{6089E83B-1F77-E411-B232-00155D644382}" />
                </filter>
                <condition attribute="statecode" operator="eq" value="0" />
            </filter>
        </filter>`

**Comment by Schui1024** [comment]
thanks for the update. I found running a crm query whilst monitoring the sql commands with server profiler gave me the bulk of the query code.. makes it an easier start.

Would still have been good to get this working.. but hey..

**Comment by abtevrythng** [comment]
⛔️ Sorry but I don't have access to dynamics CRM anymore. This Project is deprecated.
