### ISSUE TITLE
Try to convert this

### ISSUE THREAD

**Issue by MaksymBondarchuk** [abtevrythng/FetchXML-to-SQL#5]
<fetch>
  <entity name="lead" >
    <attribute name="estimatedamount_base" alias="LeadSum" />
    <attribute name="createdon" alias="LeadCreatedOn" />
    <attribute name="statecode" alias="LeadStatus" />
    <filter>
      <condition entityname="BusinessUnitOfLead" attribute="name" operator="neq" value="Packaging-PACE" />
      <condition entityname="BusinessUnitOfOpportunity" attribute="name" operator="neq" value="SomeBuName" />
    </filter>
    <link-entity name="opportunity" from="opportunityid" to="qualifyingopportunityid" link-type="outer" >
      <attribute name="statecode" alias="OpportunityStatus" />
      <attribute name="estimatedvalue_base" alias="OpportunitySum" />
      <link-entity name="businessunit" from="businessunitid" to="owningbusinessunit" link-type="outer" alias="BusinessUnitOfOpportunity" />
    </link-entity>
    <link-entity name="businessunit" from="businessunitid" to="owningbusinessunit" link-type="outer" alias="BusinessUnitOfLead" />
  </entity>
</fetch>

**Comment by txy8188** [comment]
I found a bug, the code is bellow
 string tempString = entityName + "." + myStruct.linkEntityFrom + " = " + myStruct.linkEntityFromToName + "." + myStruct.linkEntityTo ,
and the correct code is 
 string tempString = entityName + "." +myStruct.linkEntityTo + " = " + myStruct.linkEntityFromToName + "." +  myStruct.linkEntityFrom,
![tim 20180123103233](https://user-images.githubusercontent.com/15812966/35255174-bf952640-0028-11e8-9c70-aa565460edc7.png)
![tim 20180123103007](https://user-images.githubusercontent.com/15812966/35255175-bfd5a102-0028-11e8-8b4d-316367ae3c03.png)

 ,

**Comment by abtevrythng** [comment]
⛔️ Sorry but I don't have access to dynamics CRM anymore. This Project is deprecated.
