### ISSUE TITLE
I found a bug abount link-entity

### ISSUE THREAD

**Issue by VicDynamics** [abtevrythng/FetchXML-to-SQL#6]
I found a bug, the code is bellow
string tempString = entityName + "." + myStruct.linkEntityFrom + " = " + myStruct.linkEntityFromToName + "." + myStruct.linkEntityTo ,
and the correct code is
string tempString = entityName + "." +myStruct.linkEntityTo + " = " + myStruct.linkEntityFromToName + "." + myStruct.linkEntityFrom,
![tim 20180123103233](https://user-images.githubusercontent.com/15812966/35255329-752c00dc-0029-11e8-9d5e-2798d6a82b30.png)
![tim 20180123103007](https://user-images.githubusercontent.com/15812966/35255330-756ed8e4-0029-11e8-81d2-e81b5fe85c7d.png)

**Comment by xiefengdaxia** [comment]
i found this bolg had solved this problem. hope this project can keep updating.
[link](https://blog.csdn.net/vic0228/article/details/79148952?tdsourcetag=s_pcqq_aiomsg)

**Comment by abtevrythng** [comment]
⛔️ Sorry but I don't have access to dynamics CRM anymore. This Project is deprecated.
